Repository wecode-bootcamp-korea/21-1st-MealKatMarket-frontend, pull requests merged in 2021-06, with the labels that each got.

#4 [21기 강준희] Add: 헤더, 하단메뉴, 로그인, 관심상품 페이지 추가
  public/icon/Buy.svg
  public/icon/Home.svg
  public/icon/LeftArrow.svg
  public/icon/Profile.svg
  public/icon/Search.svg
  public/icon/heart.svg
  public/images/logo.png
  public/images/logo1.png
  public/images/logo3.png
  src/Routes.js
  src/components/BottomNav/BottomNav.js
  src/components/BottomNav/BottomNav.scss
  src/components/Header/Header.js
  src/components/Header/Header.scss
  src/pages/Favorite/Favorite.js
  src/pages/Favorite/Favorite.scss
  src/pages/Login/Login.js
  src/pages/Login/Login.scss
  src/styles/variables.scss
Labels: Status: Accepted

#3 [21기 박준우] Fix: 피드백 사항 반영 완료
  public/images/Buy.svg
  public/images/Buy_shadow.svg
  public/images/Home_Black.svg
  public/images/Home_Orange.svg
  public/images/LeftArrow.svg
  public/images/Profile.svg
  public/images/Search.svg
  public/images/cart_banner.png
  public/images/heart.svg
  src/Routes.js
  src/components/Footer/Footer.js
  src/components/Footer/Footer.scss
  src/components/Search/Search.js
  src/components/Search/Search.scss
  src/pages/Cart/Cart.js
  src/pages/Cart/Cart.scss
  src/pages/Register/Register.js
  src/pages/Register/Register.scss
  src/styles/variables.scss
Labels: Status: Conflict 해결 요청, Status: 리뷰 요청

#5 [21기 박준우] Fix: 검증 방식 변경
  src/pages/Register/Register.js
  src/pages/Register/Register.scss
Labels: Status: 리뷰 요청

#7 [21기 강준희] 수정사항 반영 및 Product 진행 중
  public/icon/Notification.svg
  public/icon/Star.svg
  public/icon/cart-button-40.svg
  public/icon/cart-button.svg
  public/icon/close.svg
  public/icon/heart-gray.svg
  public/images/bargain-banner.png
  public/images/donut.png
  public/images/pizza.png
  public/images/닭갈비.png
  public/images/텅.png
  src/Routes.js
  src/components/BottomNav/BottomNav.js
  src/components/BottomNav/BottomNav.scss
  src/components/FavoriteHorizontalCard/FavoriteHorizontalCard.js
  src/components/FavoriteHorizontalCard/FavoriteHorizontalCard.scss
  src/components/FavoriteVerticalCard/FavoriteVerticalCard.js
  src/components/FavoriteVerticalCard/FavoriteVerticalCard.scss
  src/components/Header/Header.js
  src/components/Modal/Modal.js
  src/components/Modal/Modal.scss
  src/components/ProductCard/ProductCard.js
  src/components/ProductCard/ProductCard.scss
  src/components/ProductCard/Status.js
  src/components/ProductCard/Status.scss
  src/components/Timer/Timer.js
  src/components/Timer/Timer.scss
  src/pages/Bargain/Bargain.js
  src/pages/Bargain/Bargain.scss
  src/pages/Favorite/Favorite.js
  src/pages/Favorite/Favorite.scss
  src/pages/Login/Login.js
  src/pages/Product/Product.js
  src/pages/Product/Product.scss
  src/styles/variables.scss
Labels: Status: 리뷰 요청, Status: 수정 요청, Status: 추가 기능 구현중

#6 [21기 박준우] Add: 상세페이지 기본 레이아웃 완료
  public/data/Project.json
  public/icon/Buy_shadow.svg
  public/icon/Close.svg
  public/icon/Home_Black.svg
  public/icon/Home_Orange.svg
  public/icon/UnderArrow.svg
  public/images/Buy.svg
  public/images/LeftArrow.svg
  public/images/Profile.svg
  public/images/Search.svg
  public/images/delivery_info.png
  public/images/fish.png
  public/images/heart.svg
  public/images/namul.jpeg
  src/Routes.js
  src/components/BottomModal/BottomModal.js
  src/components/BottomModal/BottomModal.scss
  src/components/Footer/Footer.scss
  src/components/Search/Search.js
  src/pages/Detail/Detail.js
  src/pages/Detail/Detail.scss
  src/styles/variables.scss
Labels: Status: 리뷰 요청

#8 [21기 박준우] Add: 검색 로직 구현 완료
  public/Data/testData.json
  src/components/Search/Search.js
  src/components/SearchList/SearchList.js
  src/components/SearchList/SearchList.scss
Labels: Status: 리뷰 요청

#11 [21기 박준우] Add: 아이콘에 링크 삽입
  src/pages/Register/Register.js
  src/pages/Register/Register.scss
Labels: Status: 리뷰 요청

#10 [21기 강준희] Modify: 수정사항 반영
  public/data/data.json
  public/favicon.ico
  public/icon/Swap.svg
  public/images/감바스.png
  public/images/김치볶음밥.png
  public/images/냉면.png
  public/images/만두.png
  public/images/부대찌개.png
  public/images/블루베리.png
  public/images/연어스테이크.png
  src/Routes.js
  src/components/ProductCard/Card.js
  src/components/ProductCard/Card.scss
  src/components/ProductCard/ProductCard.js
  src/components/ProductCard/ProductCard.scss
  src/components/ProductCard/Status.js
  src/components/ProductCard/Status.scss
  src/pages/Product/Product.js
  src/pages/Product/Product.scss
Labels: Status: 리뷰 요청, Status: 수정 요청

#12 [21기 박준우] Fix: 불필요한 라우팅 주소 삭제 및 아이콘 링크 추가
  src/Routes.js
  src/pages/Cart/Cart.js
Labels: Status: 리뷰 요청

#13 [21기 박준우] Add: 아이콘 라우팅 활성화, Component 각 페이지에 적용
  src/Routes.js
  src/components/BottomNav/BottomNav.scss
  src/components/Footer/Footer.scss
  src/components/Header/Header.js
  src/components/Header/Header.scss
  src/pages/Bargain/Bargain.js
  src/pages/Favorite/Favorite.js
  src/pages/Favorite/Favorite.scss
  src/pages/Product/Product.js
Labels: Status: 리뷰 요청

#14 Add: 추천 상품 Mock Data 기반 랜더링
  public/Data/RecommendData.json
  public/images/hot_choco.png
  src/Routes.js
  src/components/FavoriteVerticalCard/FavoriteVerticalCard.scss
  src/components/ProductCard/ProductCard.scss
  src/components/RecommendCard/RecommendCard.js
  src/components/RecommendCard/RecommendCard.scss
  src/pages/Cart/Cart.js
  src/pages/Cart/Cart.scss
  src/pages/SearchResult/SearchResult.js
  src/pages/SearchResult/SearchResult.scss
  src/styles/variables.scss
Labels: Status: Accepted

#15 Fix: 아이콘 링크 주소 수정
  src/Routes.js
  src/components/BottomNav/BottomNav.js
  src/components/Header/Header.js
Labels: Status: 리뷰 요청

#16 [21기 강준희] header, bottomnav 수정!
  public/images/감바스.png
  public/images/김치볶음밥.png
  public/images/냉면.png
  public/images/만두.png
  public/images/부대찌개.png
  public/images/블루베리.png
  public/images/연어스테이크.png
  src/Routes.js
  src/components/BottomNav/BottomNav.js
  src/components/BottomNav/BottomNav.scss
  src/components/FavoriteVerticalCard/FavoriteVerticalCard.js
  src/components/FavoriteVerticalCard/FavoriteVerticalCard.scss
  src/components/Header/Header.js
  src/components/Header/Header.scss
  src/components/Modal/Modal.scss
  src/components/ProductCard/Card.js
  src/pages/Bargain/Bargain.js
  src/pages/Bargain/Bargain.scss
  src/pages/Favorite/Favorite.js
  src/pages/Favorite/Favorite.scss
  src/pages/Login/Login.js
  src/pages/Main/Main.js
  src/pages/Main/Main.scss
  src/pages/Product/Product.js
  src/pages/Product/Product.scss
  src/pages/data.json
Labels: Status: 리뷰 요청

#20 [21기 박준우] Add: 인증, 데이터 키값 수정, 라우팅 주소 수정, 아이콘 링크 주소 수정
  public/images/쿠캣당일발송.png
  src/Routes.js
  src/components/BottomModal/BottomModal.js
  src/components/BottomNav/BottomNav.js
  src/components/Header/Header.js
  src/components/RecommendCard/RecommendCard.js
  src/components/Search/Search.js
  src/components/SearchList/SearchList.js
  src/pages/Detail/Detail.js
  src/pages/Detail/Detail.scss
  src/pages/Product/Product.js
  src/pages/SearchResult/SearchResult.js
Labels: Status: 리뷰 요청

#22 Add: 최종 커밋
  public/icon/heart-full.svg
  src/Routes.js
  src/components/BottomModal/BottomModal.js
  src/components/RecommendCard/RecommendCard.js
  src/components/Search/Search.js
  src/components/SearchList/SearchList.js
  src/pages/Detail/Detail.js
  src/pages/Detail/Detail.scss
  src/pages/Login/Login.js
  src/pages/SearchResult/SearchResult.js
Labels: Status: 리뷰 요청

#21 [21기 강준희]최종 커밋!
  public/icon/heart-empty.svg
  src/Routes.js
  src/components/BottomNav/BottomNav.scss
  src/components/FavoriteHorizontalCard/FavoriteHorizontalCard.js
  src/components/FavoriteHorizontalCard/FavoriteHorizontalCard.scss
  src/components/Header/Header.scss
  src/components/ProductCard/Card.js
  src/components/ProductCard/List.js
  src/components/ProductCard/Status.js
  src/components/Timer/Timer.js
  src/pages/Bargain/Bargain.js
  src/pages/Bargain/Bargain.scss
  src/pages/Cart/Cart.js
  src/pages/Favorite-my/FavoriteMy.js
  src/pages/Favorite-my/FavoriteMy.scss
  src/pages/Login/Login.js
  src/pages/Product/Product.js
  src/pages/Product/Product.scss
  src/pages/ProductTest/ProductTest.js
  src/pages/ProductTest/ProductTest.scss
Labels: Status: Accepted
